# Home Assistant Operating System pull-request checks

name: PR checks

on: [pull_request]

jobs:
  linters:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Check Dockerfile
      uses: brpaz/hadolint-action@v1.5.0
      with:
        dockerfile: Dockerfile

    - name: Check shell scripts
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        ignore_paths: buildroot

    - name: Check buildroot-external packages
      run: |
        buildroot/utils/check-package --exclude PackageHeader --br2-external buildroot-external/package/*/*
